apiVersion: v1
kind: Secret
metadata:
  name: container-registry
type: Opaque
data:
  credential: 8f928765-82f7-4384-b8b2-5f051edeed5a:eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiI4ZjkyODc2NS04MmY3LTQzODQtYjhiMi01ZjA1MWVkZWVkNWEiLCJhdWQiOiI4ZjkyODc2NS04MmY3LTQzODQtYjhiMi01ZjA1MWVkZWVkNWEiLCJvcmdEb21haW4iOiJvcGluaW9uZ2lzdCIsIm5hbWUiOiJDSVwvQ0QiLCJpc3MiOiJodHRwczpcL1wvb3Bpbmlvbmdpc3QuamV0YnJhaW5zLnNwYWNlIiwicGVybV90b2tlbiI6IjNqd3hhdjRZd1QxTiIsInByaW5jaXBhbF90eXBlIjoiU0VSVklDRSIsImlhdCI6MTY3ODE3NDc5MH0.KWmtiVwazQ8xjaOHF_69EOyu32fPumbK5KglCAn-gJW1_MhA_fPlIi_9RCv378xkqE8soztl1Qc-ApgWUovzodGR2xrjuGpO47iN_IYUWLufMeOFQumKfyCgbYeiX6lYcsN21IiTieTQo2Akx5_FcXPnZOelGuPMfYRPO2Pcpqk