apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
data:
  registries.conf: |
    registries:
    - name: Jetbrain Space
      api_url: https://opiniongist.registry.jetbrains.space
      prefix: jetbrains.space
      credentials: secret:argocd/container-registry#credential