apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: cicd-cluster/chart
    repoURL: https://github.com/github4sanjay/eks-cluster-manifests.git
    targetRevision: HEAD
  project: cicd-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true